
[openSky]
username = ''
apikey = ''
endpoint = 'https://opensky-network.org/api/states/all'

[network]
host = '10.42.0.1'
socket = 65432

[geofence]
lamin = '44.915368'
lamax = '44.928452'
lomin = '-93.308671'
lomax = '-93.277638'

[gui]
montageW = 3
montageH = 1

[data]
regDB = 'acdb.csv'
imageFolder = '~/airplanes'

[mobileNet]
prototxt = 'prototxt'
model = 'model'
confidence = 0.2
CLASSES= ["background",
          "aeroplane",
          "bicycle",
          "bird",
          "boat",
          "bottle",
          "bus",
          "car",
          "cat",
          "chair",
          "cow",
          "diningtable",
          "dog",
          "horse",
          "motorbike",
          "person",
          "pottedplant",
          "sheep",
          "sofa",
          "train",
          "tvmonitor"]
CONSIDER=["aeroplane"]
