bb = [ "108", "140", "192", "194",]
imagename = "/home/nvidia/airplanes/17.jpg"

[record]
categoryDescription = ""
operatoriata = ""
registered = ""
id = 291758
modes = "false"
manufacturername = "Airbus"
operatorcallsign = ""
linenumber = ""
adsb = "false"
status = ""
acars = "false"
testreg = ""
serialnumber = "8810"
reguntil = "2022-03-31"
owner = "Bank Of Utah Trustee"
icaoaircrafttype = ""
operatoricao = ""
model = "A321-211"
seatconfiguration = ""
engines = "CFM INTL CFM56-5B3/3"
registration = "N374DX"
typecode = ""
operator = ""
built = "2019-01-01"
manufacturericao = ""
icao24 = "a44308"
notes = ""
firstflightdate = ""
